name: Node
on:
  pull_request:
    branches:
    - main
    - release-*
  push:
    branches:
    - main
    - release-*

jobs:
  yarn:
    name: Run Node checks
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - name: Set up Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22
    - run: yarn install
      working-directory: client/web/antrea-ui/
    - run: yarn lint
      working-directory: client/web/antrea-ui/
    - run: yarn test
      working-directory: client/web/antrea-ui/
